---
# Allow builds to run for up to 30 minutes.
timeout: 1800s

steps:

# Build 7.3 images.

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 73-pull
    waitFor: ['-']
    args: ['-c', 'docker pull $_DOCKER_HUB_REPO/php:7.3-fpm || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-pull]
    id: 73-build
    args: ['build', '-t', 'build/php:7.3-fpm', '--cache-from', '$_DOCKER_HUB_REPO/php:7.3-fpm', '--build-arg', 'SRC_TAG=7.3.3-fpm-alpine3.9', '.']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-build]
    args: ['tag', 'build/php:7.3-fpm', '$_DOCKER_HUB_REPO/php:7.3-fpm']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-build]
    id: 73-tag
    entrypoint: 'bash'
    args: ['-c', 'docker tag build/php:7.3-fpm "$_DOCKER_HUB_REPO/php:7.3-fpm-$(date +%Y%m%d)"']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    waitFor: [73-pull]
    id: 73-composer-pull
    args: ['-c', 'docker pull $_DOCKER_HUB_REPO/php:7.3-fpm-composer || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-composer-pull, 73-build]
    id: 73-composer-build
    args: ['build', '-t', 'build/php:7.3-fpm-composer', '--cache-from', '$_DOCKER_HUB_REPO/php:7.3-fpm-composer', '--build-arg', 'PHP_VERSION=7.3', '-f', 'Dockerfile-composer', '.']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-composer-build]
    args: ['tag', 'build/php:7.3-fpm-composer', '$_DOCKER_HUB_REPO/php:7.3-fpm-composer']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-composer-build]
    id: 73-composer-tag
    entrypoint: 'bash'
    args: ['-c', 'docker tag build/php:7.3-fpm-composer "$_DOCKER_HUB_REPO/php:7.3-fpm-composer-$(date +%Y%m%d)"']


# Build 7.2 images.

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 72-pull
    waitFor: ['-']
    args: ['-c', 'docker pull $_DOCKER_HUB_REPO/php:7.2-fpm || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [72-pull]
    id: 72-build
    args: ['build', '-t', 'build/php:7.2-fpm', '--cache-from', '$_DOCKER_HUB_REPO/php:7.2-fpm', '--build-arg', 'SRC_TAG=7.2.19-fpm-alpine3.9', '.']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [72-build]
    args: ['tag', 'build/php:7.2-fpm', '$_DOCKER_HUB_REPO/php:7.2-fpm']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [72-build]
    entrypoint: 'bash'
    id: 72-tag
    args: ['-c', 'docker tag build/php:7.2-fpm "$_DOCKER_HUB_REPO/php:7.2-fpm-$(date +%Y%m%d)"']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    waitFor: [72-pull]
    id: 72-composer-pull
    args: ['-c', 'docker pull $_DOCKER_HUB_REPO/php:7.2-fpm-composer || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [72-composer-pull, 72-build]
    id: 72-composer-build
    args: ['build', '-t', 'build/php:7.2-fpm-composer', '--cache-from', '$_DOCKER_HUB_REPO/php:7.2-fpm-composer', '--build-arg', 'PHP_VERSION=7.2', '-f', 'Dockerfile-composer', '.']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [72-composer-build]
    args: ['tag', 'build/php:7.2-fpm-composer', '$_DOCKER_HUB_REPO/php:7.2-fpm-composer']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [72-composer-build]
    entrypoint: 'bash'
    id: 72-composer-tag
    args: ['-c', 'docker tag build/php:7.2-fpm-composer "$_DOCKER_HUB_REPO/php:7.2-fpm-composer-$(date +%Y%m%d)"']

# Login and push images.
  - name: 'gcr.io/cloud-builders/gcloud'
    id: decrypt-hub-username
    args:
      - 'kms'
      - 'decrypt'
      - '--location=global'
      - '--keyring=docker'
      - '--key=hub'
      - '--ciphertext-file=.cloudbuild/docker-hub-username.enc'
      - '--plaintext-file=docker-hub-username.txt'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: decrypt-hub-password
    args:
      - 'kms'
      - 'decrypt'
      - '--location=global'
      - '--keyring=docker'
      - '--key=hub'
      - '--ciphertext-file=.cloudbuild/docker-hub-password.enc'
      - '--plaintext-file=docker-hub-password.txt'

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-tag, 72-tag, 73-composer-tag, 72-composer-tag, decrypt-hub-username, decrypt-hub-password]
    entrypoint: 'bash'
    args: ['-c', 'cat docker-hub-password.txt | docker login --username=$$(cat docker-hub-username.txt) --password-stdin']

images:
  - '$_DOCKER_HUB_REPO/php'
