on:
  push:
    branches: [actions]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "7.2"
        variant:
          - "fpm"
          - "cli"
        include:
        - version: "7.2"
          variant: "fpm"
          source_image: "php:7.2.32-fpm-alpine3.12"
        - version: "7.2"
          variant: "cli"
          source_image: "php:7.2.32-zts-alpine3.12"
#        - version: 7.3
#          image: "php:7.3.20-fpm-alpine3.12"
#        - version: 7.4
#          image: "php:7.4.8-fpm-alpine3.12"
#        - version: 8.0
#          image: "php:8.0.0alpha2-fpm-alpine3.12"
    steps:
    - uses: actions/checkout@v2

    - name: build variant
      run: |
        docker build \
          -t build/php:${{ matrix.version }}-${{ matrix.variant }} \
          --build-arg IMAGE=${{ matrix.source_image }} \
          -f Dockerfile \
          .

    - name: build nginx
      if: "matrix.variant == 'fpm'"
      run: |
        docker build \
          -t build/php:${{ matrix.version }}-nginx \
          --build-arg IMAGE=build/php:${{ matrix.version }}-${{ matrix.variant }} \
          -f Dockerfile-nginx \
          .

    - name: save images
      run: |
        images=("build/php:${{ matrix.version }}-${{ matrix.variant }}")
        [[ "${{ matrix.variant }}" = "fpm" ]] && images+=("build/php:${{ matrix.version }}-nginx")

        docker save -o /tmp/docker.tar "${images[@]}"

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        retention-days: 1
        name: docker-${{ matrix.version }}-${{ matrix.variant }}
        path: /tmp/docker.tar

  push:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        version:
        - "7.2"
        variant:
        - "fpm"
        - "cli"
    steps:
    - name: log in (docker hub)
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: download image
      uses: actions/download-artifact@v2
      with:
        name: docker-${{ matrix.version }}-${{ matrix.variant }}.tar
        path: /tmp

    - name: load image
      run: docker load -i /tmp/docker.tar
#
#    - name: list images
#      run: docker images
#    - name: push variant
#      run: |
#        docker push ${{ github.repository_owner }}/php-testing:${{ matrix.version }}-${{ matrix.variant }}
#
#    - name: push nginx
#      if: "matrix.variant == 'fpm'"
#      run: |
#        docker push ${{ github.repository_owner }}/php-testing:${{ matrix.version }}-nginx
